import React,{useEffect,useMemo,useState}from"react";import{createRoot}from"react-dom/client";import axios from"axios";import{LayoutDashboard,CheckSquare,Users,CalendarDays,Plus,Search,Bell,Clock3,CheckCircle2,Circle,ChevronDown}from"lucide-react";import"./styles.css";
const API="http://localhost:8080/api";const initial={title:"",description:"",status:"TODO",priority:"MEDIUM",project:"TaskFlow",dueDate:""};
function App(){const[tasks,setTasks]=useState([]),[q,setQ]=useState(""),[filter,setFilter]=useState("ALL"),[show,setShow]=useState(false),[form,setForm]=useState(initial),[error,setError]=useState("");
const load=()=>axios.get(API+"/tasks").then(r=>setTasks(r.data)).catch(()=>setError("Start Spring Boot on port 8080. You also need MySQL configured. "));useEffect(()=>load(),[]);
const f=useMemo(()=>tasks.filter(t=>(filter==="ALL"||t.status===filter)&&(`${t.title} ${t.description||""}`).toLowerCase().includes(q.toLowerCase())),[tasks,q,filter]);
const stats={all:tasks.length,todo:tasks.filter(t=>t.status==="TODO").length,progress:tasks.filter(t=>t.status==="IN_PROGRESS").length,done:tasks.filter(t=>t.status==="DONE").length};
async function save(e){e.preventDefault();await axios.post(API+"/tasks",form);setShow(false);setForm(initial);load()}
async function change(id,status){const t=tasks.find(x=>x.id===id);await axios.put(API+"/tasks/"+id,{...t,status});load()}
return <div className="app"><aside><div className="logo"><b>TF</b><strong>Task<span>Flow</span></strong></div><nav><a className="active"><LayoutDashboard/>Overview</a><a><CheckSquare/>My Tasks <i>{stats.all}</i></a><a><Users/>Team</a><a><CalendarDays/>Calendar</a></nav><div className="space"><small>WORKSPACE</small><p>● TaskFlow Project <ChevronDown/></p></div><div className="user"><span>B</span><div><b>Balaji</b><small>Developer</small></div></div></aside>
<main><header><div className="search"><Search/><input placeholder="Search tasks..." value={q} onChange={e=>setQ(e.target.value)}/></div><div><Bell className="bell"/><button className="avatar">B</button></div></header><section><div className="heading"><div><small>WORKSPACE / OVERVIEW</small><h1>Good morning, Balaji 👋</h1><p>Manage tasks, deadlines and team collaboration from one workspace.</p></div><button className="create" onClick={()=>setShow(true)}><Plus/> Create task</button></div>{error&&<div className="error">{error}</div>}
<div className="stats"><Stat n={stats.all} t="Total tasks" s="Across the workspace"/><Stat n={stats.progress} t="In progress" s="Currently active"/><Stat n={stats.done} t="Completed" s="Finished tasks"/><Stat n={stats.todo} t="To do" s="Awaiting work"/></div>
<div className="toolbar"><div>{["ALL","TODO","IN_PROGRESS","DONE"].map(x=><button className={filter===x?"sel":""} onClick={()=>setFilter(x)}>{x==="IN_PROGRESS"?"IN PROGRESS":x}</button>)}</div><span>Recently updated <ChevronDown/></span></div>
<div className="list">{f.map(t=><article className="task"><div className={"status "+t.status.toLowerCase()}>{t.status==="DONE"?<CheckCircle2/>:t.status==="IN_PROGRESS"?<Clock3/>:<Circle/>}</div><div><div className="title"><h3>{t.title}</h3><em className={t.priority.toLowerCase()}>{t.priority}</em></div><p>{t.description||"No description provided."}</p><small>{t.project||"TaskFlow"} {t.dueDate&&" · Due "+t.dueDate}</small></div><select value={t.status} onChange={e=>change(t.id,e.target.value)}><option value="TODO">To do</option><option value="IN_PROGRESS">In progress</option><option value="DONE">Done</option></select></article>)}{!f.length&&<div className="empty">No tasks found. Create a task to get started.</div>}</div></section></main>
{show&&<div className="back"><form onSubmit={save}><button type="button" className="x" onClick={()=>setShow(false)}>×</button><h2>Create task</h2><label>Title<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Description<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><div className="two"><label>Priority<select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}><option>LOW</option><option>MEDIUM</option><option>HIGH</option></select></label><label>Due date<input type="date" value={form.dueDate} onChange={e=>setForm({...form,dueDate:e.target.value})}/></label></div><button className="create full">Create task</button></form></div>}</div>}
function Stat({n,t,s}){return <div className="stat"><b>{n}</b><div><strong>{t}</strong><small>{s}</small></div></div>}createRoot(document.getElementById("root")).render(<App/>);
