CREATE DATABASE IF NOT EXISTS taskflow; USE taskflow;
CREATE TABLE IF NOT EXISTS users(id BIGINT AUTO_INCREMENT PRIMARY KEY,email VARCHAR(255) UNIQUE NOT NULL,password VARCHAR(255) NOT NULL,full_name VARCHAR(255),role VARCHAR(50));
CREATE TABLE IF NOT EXISTS tasks(id BIGINT AUTO_INCREMENT PRIMARY KEY,title VARCHAR(255) NOT NULL,description VARCHAR(2000),status VARCHAR(30),priority VARCHAR(30),due_date DATE,assignee_id BIGINT,created_by BIGINT,project VARCHAR(255));
CREATE TABLE IF NOT EXISTS comments(id BIGINT AUTO_INCREMENT PRIMARY KEY,task_id BIGINT,user_id BIGINT,message VARCHAR(2000),created_at DATETIME);
